
services:
  new-api:
    image: registry.cn-zhangjiakou.aliyuncs.com/fengzhihao/tool:calciumion-new-api-0.12.6-2026_04_10_102952
    environment:
      TZ: Asia/Shanghai
      SQL_DSN: root:nFGmYeL3ay88QsOe@tcp(172.29.64.1:3306)/new-api 
      GLOBAL_API_RATE_LIMIT_ENABLE: false
    volumes:
      - C:\Docker\new-api\data:/data 
      - C:\Project\github\new-api:/build
    ports:
      - "23000:3000"
    command: ["sleep","100d"]
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
